### ISSUE TITLE
Some requests fail for AudioPlayer skill with no handler found

### ISSUE THREAD

**Issue by Saandji** [alexa/alexa-skills-kit-sdk-for-java#107]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I've implemented the skill using this new SDK. The skill is using AudioPlayer interface. So far, the skill works without any issues, but everytime my skill gets invoked, I see that I have one execution of my Lambda function, which failes with error:

`Unable to find a suitable request handler`

## Expected Behavior
I expect my skill to work without unexpected Exceptions, or at least have the meaninful error to be logged, so I can fix the issue. 

## Current Behavior

Currently, I get one Lambda execution with next logs:

Before I created the Exception handler:

```
2018-05-07 20:53:26 [ERROR] <b052c265-5238-11e8-803c-cb2b083b0db9> DefaultRequestDispatcher:97 - [amzn1.echo-api.request.b80e1411-524c-4811-812d-4905ed0bb6d3] Unable to find a suitable request handler
com.amazon.ask.exception.AskSdkException: [amzn1.echo-api.request.b80e1411-524c-4811-812d-4905ed0bb6d3] Unable to find a suitable request handler
at com.amazon.ask.dispatcher.impl.DefaultRequestDispatcher.doDispatch(DefaultRequestDispatcher.java:98)
at com.amazon.ask.dispatcher.impl.DefaultRequestDispatcher.dispatch(DefaultRequestDispatcher.java:68)
at com.amazon.ask.Skill.invoke(Skill.java:87)
at com.amazon.ask.Skill.invoke(Skill.java:62)
at com.amazon.ask.SkillStreamHandler.handleRequest(SkillStreamHandler.java:67)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:283)
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:94)
```

after I created the Exception interceptor trying to log something meaningful:
the interceptor code:
```
class ExceptionLogHandler : ExceptionHandler {
    private val log = KotlinLogging.logger {}
    override fun canHandle(input: HandlerInput, throwable: Throwable): Boolean {
        return true
    }

    override fun handle(input: HandlerInput, throwable: Throwable): Optional<Response> {
        if (throwable is AskSdkException) {
            log.error("Got SDK exception for input= ${objectMapper.writeValueAsString(input)}")
        } else {
            log.error("An error occurred while processing the request for skillId=${input.skillId}", throwable)
        }
        return input.responseBuilder
                .withSpeech(getExceptionResponse(input.locale))
                .build()
    }

    private fun getExceptionResponse(locale: String): String {
        return "some error message to the user here"
    }
}
```
Unfortunately, it breaks to log the HandlerInput as json string with next message: 
```
2018-05-07 21:13:07 [ERROR] <701d817b-523b-11e8-a1d7-41c0c74c0058> DefaultRequestDispatcher:97 - [amzn1.echo-api.request.7c7ae24a-bb8f-4933-b95e-bcc206aa319e] Unable to find a suitable request handler
Attempting to read session attributes from out of session request (through reference chain: com.amazon.ask.dispatcher.request.handler.HandlerInput["attributesManager"]->com.amazon.ask.attributes.AttributesManager["sessionAttributes"]): com.fasterxml.jackson.databind.JsonMappingException
com.fasterxml.jackson.databind.JsonMappingException: Attempting to read session attributes from out of session request (through reference chain: com.amazon.ask.dispatcher.request.handler.HandlerInput["attributesManager"]->com.amazon.ask.attributes.AttributesManager["sessionAttributes"])
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3893)
at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3207)
at com.saandji.alexa.audio.skill.handlers.exception.ExceptionLogHandler.handle(ExceptionLogHandler.kt:21)
at com.amazon.ask.dispatcher.impl.DefaultRequestDispatcher.dispatch(DefaultRequestDispatcher.java:73)
at com.amazon.ask.Skill.invoke(Skill.java:87)
at com.amazon.ask.Skill.invoke(Skill.java:62)
at com.amazon.ask.SkillStreamHandler.handleRequest(SkillStreamHandler.java:67)
Caused by: java.lang.IllegalStateException: Attempting to read session attributes from out of session request
at com.amazon.ask.attributes.AttributesManager.getSessionAttributes(AttributesManager.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:687)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
... 13 more
```

not sure for the question above

I would expect the SDK to log the error and tell me what kind of Handler it is expect to see if the Handler was not found. At least the request type or some more meaninful information. 

## Steps to Reproduce (for bugs)

I will follow up this Issue, if you will need my help to reproduce the bug, i can share the code privately, with you for debugging/root causing.

```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```

## Possible Solution

N/A at the moment

```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```

## Context

The issue effected me in the way, that I am not sure that the skill handles all required requests from Alexa, since it is working just fine, but I constantly see these errors in CloudWatch.

this is the list of my handlers: I won't publish the whole implementation here, but the class names reflect the RequestType coming from Alexa.

```kotlin
 //audio
                        OnPlaybackFailedRequestHandler(),
                        OnPlaybackStartedRequestHandler(),
                        OnPlaybackNearlyFinishedRequestHandler(),
                        OnPlaybackFinishedRequestHandler(),
                        OnPlaybackStoppedRequestHandler(),
                        OnPlayCommandIssuedRequestHandler(),
                        OnNextCommandIssuedRequestHandler(),
                        OnPauseCommandIssuedRequestHandler(),
                        OnPreviousCommandIssuedRequestHandler(),

                        //default
                        LaunchRequestHandler(),
                        //custom handler to handle all my custom audio intents, not relevant for this bug
                        AudioIntentsRequestHandler(), 
                        SessionEndedRequestHandler(),
                        CancelStopPauseIntentsHandler(),
                        HelpIntentHandler())
```

## Your Environment

Java: 1.8
Kotlin: 1.2.41
Lambda environment
Ask SDK version: 2.0.2

## Java Info

* Java version used for development: 1.8

**Comment by Saandji** [comment]
So I managed to log the Request object in my ExceptionHandler. Here's the request, unfortunately I'm not sure how it is possible to get error "SpeechletResponse was null", since I'm passing the Optional everywhere

```json
{
    "type": "System.ExceptionEncountered",
    "requestId": "amzn1.echo-api.request.3155b930-f6c2-455b-8bf5-e045fde9008d",
    "timestamp": {
        "offset": {
            "totalSeconds": 0,
            "id": "Z",
            "rules": {
                "transitions": [
                    "java.util.ArrayList",
                    []
                ],
                "transitionRules": [
                    "java.util.ArrayList",
                    []
                ],
                "fixedOffset": true
            }
        },
        "year": 2018,
        "month": "MAY",
        "dayOfMonth": 7,
        "dayOfWeek": "MONDAY",
        "dayOfYear": 127,
        "monthValue": 5,
        "hour": 21,
        "minute": 42,
        "nano": 0,
        "second": 33
    },
    "locale": "en-US",
    "error": {
        "type": "INVALID_RESPONSE",
        "message": "SpeechletResponse was null"
    },
    "cause": {
        "requestId": "amzn1.echo-api.request.5ac913ab-9d55-4a4c-bc9e-415e795c36a1"
    }
}
```

**Comment by sungolivia** [comment]
Hi there, would you be able to share your stream handler and handlers code?

**Comment by Saandji** [comment]
Shared the code privately. 

I also doubled check the AudioPlayer documentation, and found this: https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#system-exceptionencountered

Which is partially explains why I get this error:
`[ERROR] <52a097fd-528e-11e8-9f5d-7f29da1a9226> DefaultRequestDispatcher:97 - [amzn1.echo-api.request.f5821072-94f2-4557-a8aa-a7d65cd8f740] Unable to find a suitable request handler`

Because I do not have a Handler for `System.ExceptionEncountered Request`, but still a little bit frustrating for me why I'm getting this error in the body:

```
...
"error": {
        "type": "INVALID_RESPONSE",
        "message": "SpeechletResponse was null"
    }
...
```

**Comment by sungolivia** [comment]
Do you happen to know which request handler this happens at? If so, do you set withShouldEndSession in your response builder (if you do use response builder)?

**Comment by Saandji** [comment]
Double checked the code and everything seems correct for me. Actually, this Issue seems to be related to this one: https://forums.developer.amazon.com/questions/49211/system-error-speechletresponse-was-null.html
